spring.application.name=backend

# Disable database (important for now)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JWT
music.app.jwtSecret=SecretKeyToGenJWTsSecretKeyToGenJWTsSecretKeyToGenJWTsSecretKeyToGenJWTs
music.app.jwtExpirationMs=86400000

# Render port config
server.port=${PORT:8080}
server.address=0.0.0.0